namespace CarLogic
{
	public enum RaceProtocol : byte
	{
		GAME_MSG_BEGIN,
		PLAYER_ENTER_ROOM_C,
		PLAYER_EXIT_ROOM_CS,
		PLAYER_CHECK_CONNECTION_CS,
		PLAYER_SYNC_POS_CS,
		PLAYER_SYNC_FINAL_POS_CS,
		PLAYER_CORRECT_POS_S,
		PLAYER_REACH_ENDPOINT_CS,
		PLAYER_USE_ITEM_CS,
		PLAYER_AI_REQUEST_C,
		PLAYER_AI_RESPONSE_S,
		ROOM_GET_INFO_S,
		ROOM_GAME_START_S,
		ROOM_GAME_OVER_S,
		ROOM_GAME_RESULT_S,
		PLAYER_HIT_PASSIVE_ITEM_CS,
		PLAYER_GAIN_GAS,
		PLAYER_ITEM_BREAK_C
	}
}
